#!/bin/bash

set -e

CONTRIB="$(dirname "$(readlink -e "$0")")"
ROOT_FOLDER="$CONTRIB"/..
PACKAGES="$ROOT_FOLDER"/packages/
LOCALE="$ROOT_FOLDER"/electrum_nmc/locale/

if [ ! -d "$LOCALE" ]; then
  echo "Run make_locale first!"
  exit 1
fi

if [ ! -d "$PACKAGES" ]; then
  echo "Run make_packages first!"
  exit 1
fi

(
    cd "$ROOT_FOLDER"

    echo "'git clean -fx' would delete the following files: >>>"
    git clean -fx --dry-run
    echo "<<<"

    # we could build the kivy atlas potentially?
    #(cd electrum_nmc/gui/kivy/; make theming) || echo "building kivy atlas failed! skipping."

    python3 setup.py --quiet sdist --format=zip,gztar,xztar
)

ELECTRUM_VERSION=$(python3 -c "import importlib.util; version_spec = importlib.util.spec_from_file_location('version', 'electrum_nmc/version.py'); version_module = version = importlib.util.module_from_spec(version_spec); version_spec.loader.exec_module(version_module); print(version.ELECTRUM_VERSION)")
mkdir -p tmp
tar --xz -xf dist/Electrum-NMC-${ELECTRUM_VERSION}.tar.xz --directory=tmp
rm -r tmp/Electrum-NMC-${ELECTRUM_VERSION}/electrum_nmc/gui/
rm -r tmp/Electrum-NMC-${ELECTRUM_VERSION}/electrum_nmc/plugins/*/
rm -r tmp/Electrum-NMC-${ELECTRUM_VERSION}/electrum_nmc/locale/
rm -r tmp/Electrum-NMC-${ELECTRUM_VERSION}/packages/qdarkstyle/
tar --xz -cf dist/Electrum-NMC-daemon-${ELECTRUM_VERSION}.tar.xz --directory=tmp Electrum-NMC-${ELECTRUM_VERSION}
rm -r tmp
