#!/bin/bash

set -e

CONTRIB_SDIST="$(dirname "$(readlink -e "$0")")"
CONTRIB="$CONTRIB_SDIST"/../..
ROOT_FOLDER="$CONTRIB"/..
PACKAGES="$ROOT_FOLDER"/packages/
LOCALE="$ROOT_FOLDER"/electrum_nmc/electrum/locale

if [ ! -d "$PACKAGES" ]; then
  echo "Run make_packages first!"
  exit 1
fi

git submodule update --init

(
    # By default, include both source (.po) and compiled (.mo) locale files in the source dist.
    # Set option OMIT_UNCLEAN_FILES=1 to exclude the compiled locale files
    # see https://askubuntu.com/a/144139 (also see MANIFEST.in)
    rm -rf "$LOCALE"
    cp -r "$CONTRIB/deterministic-build/electrum-locale/locale/" "$LOCALE/"
    if ([ "$OMIT_UNCLEAN_FILES" != 1 ]); then
      "$CONTRIB/build_locale.sh" "$LOCALE"
    fi
)

if ([ "$OMIT_UNCLEAN_FILES" = 1 ]); then
  rm "$ROOT_FOLDER/electrum/paymentrequest_pb2.py"
fi

(
    cd "$ROOT_FOLDER"

    echo "'git clean -fd' would delete the following files: >>>"
    git clean -fd --dry-run
    echo "<<<"

    # we could build the kivy atlas potentially?
    #(cd electrum_nmc/electrum/gui/kivy/; make theming) || echo "building kivy atlas failed! skipping."

    find -exec touch -h -d '2000-11-11T11:11:11+00:00' {} +

    # note: .zip sdists would not be reproducible due to https://bugs.python.org/issue40963
    if ([ "$OMIT_UNCLEAN_FILES" = 1 ])
        then PY_DISTDIR="dist/_sourceonly" # The DISTDIR variable of this script is only used to find where the output is *finally* placed.
        else PY_DISTDIR="dist"
    fi
    TZ=UTC faketime -f '2000-11-11 11:11:11' python3 setup.py --quiet sdist --format=gztar --dist-dir="$PY_DISTDIR"
    if ([ "$OMIT_UNCLEAN_FILES" = 1 ]); then
        for fn in "$DISTDIR/_sourceonly/"*; do
            # Since ELECTRUM_VERSION is not available to us in this script, we have to use a regex.
            # Expression 1: Electrum-X.Y.Z.tar.gz -> Electrum-sourceonly-X.Y.Z.tar.gz
            #   Capture group \1 = Electrum
            #   Capture group \2 = X.Y.Z.tar.gz
            # Expression 2: dist/_sourceonly/X.tar.gz -> dist/X.tar.gz
            mv "$fn" $(sed \
                -e 's/\(.*\)-\([^-]*\)/\1-sourceonly-\2/' \
                -e 's/\/_sourceonly//' \
                <<< "$fn")
        done
        rmdir "$PY_DISTDIR"
    fi
)
