#!/bin/bash

set -e

CONTRIB_SDIST="$(dirname "$(readlink -e "$0")")"
CONTRIB="$CONTRIB_SDIST"/../..
ROOT_FOLDER="$CONTRIB"/..
PACKAGES="$ROOT_FOLDER"/packages/
LOCALE="$ROOT_FOLDER"/electrum_nmc/electrum/locale

if [ ! -d "$PACKAGES" ] && [ "$OMIT_UNCLEAN_FILES" != 1 ]; then
  echo "Run make_packages first!"
  exit 1
fi

git submodule update --init

(
    # By default, include both source (.po) and compiled (.mo) locale files in the source dist.
    # Set option OMIT_UNCLEAN_FILES=1 to exclude the compiled locale files
    # see https://askubuntu.com/a/144139 (also see MANIFEST.in)
    rm -rf "$LOCALE"
    cp -r "$CONTRIB/deterministic-build/electrum-locale/locale/" "$LOCALE/"
    if ([ "$OMIT_UNCLEAN_FILES" != 1 ]); then
      "$CONTRIB/build_locale.sh" "$LOCALE"
    fi
)

if ([ "$OMIT_UNCLEAN_FILES" = 1 ]); then
    # FIXME side-effecting repo... though in practice, this script probably runs in fresh_clone
    rm -f "$ROOT_FOLDER/electrum_nmc/electrum/paymentrequest_pb2.py"
fi

(
    cd "$ROOT_FOLDER"

    # we could build the kivy atlas potentially?
    #(cd contrib/android/; make theming) || echo "building kivy atlas failed! skipping."

    find -exec touch -h -d '2000-11-11T11:11:11+00:00' {} +

    # note: .zip sdists would not be reproducible due to https://bugs.python.org/issue40963
    if ([ "$OMIT_UNCLEAN_FILES" = 1 ])
        then PY_DISTDIR="dist/_sourceonly" # The DISTDIR variable of this script is only used to find where the output is *finally* placed.
        else PY_DISTDIR="dist"
    fi
    TZ=UTC faketime -f '2000-11-11 11:11:11' python3 setup.py --quiet sdist --format=gztar,xztar --dist-dir="$PY_DISTDIR"
    if ([ "$OMIT_UNCLEAN_FILES" = 1 ]); then
        python3 <<EOF
import importlib.util
import os

# load version.py; needlessly complicated alternative to "imp.load_source":
version_spec = importlib.util.spec_from_file_location('version', 'electrum_nmc/electrum/version.py')
version_module = importlib.util.module_from_spec(version_spec)
version_spec.loader.exec_module(version_module)

VER = version_module.ELECTRUM_VERSION
os.rename(f"dist/_sourceonly/Electrum-NMC-{VER}.tar.gz", f"dist/Electrum-NMC-sourceonly-{VER}.tar.gz")
os.rename(f"dist/_sourceonly/Electrum-NMC-{VER}.tar.xz", f"dist/Electrum-NMC-sourceonly-{VER}.tar.xz")
EOF
        rmdir "$PY_DISTDIR"
    fi
)
